const RecipeData =[
  {
    id: "1",
    name: "Pizza Margheritta",
    details: ["Flour dough ", "Basic marinara ", "Mozarella"],
    time: "30",
    src: 'https://picsum.photos/200/300?random=1',
    tools: ["cog"],
    ingredients: ["Dough", "Sauce", "Toppings"],
  },
  {
    id: "2",
    name: "Spaghetti Bolognese",
    details: ["Pasta", "Bolognese sauce", "Parmesan"],
    time: "10",
    src: 'https://picsum.photos/200/300?random=2',
    tools: ["cog"],
    ingredients: ["Pasta", "Sauce", "Cheese"],
  },
  {
    id: "3",
    name: "Burger",
    details: [""],
    time: "20",
    src: 'https://picsum.photos/200/300?random=3',
    tools: ["cog"],
    ingredients: ["Beans", "Onion", "Tomato", "Burger", "BBQ sauce", "Salad"],
  },
  {
    id: "4",
    name: "Rosti",
    details: [""],
    time: "20",
    src: 'https://picsum.photos/200/300?random=4',
    tools: ["cog"],
    ingredients: ["Potato", "Butter"],
  },
  {
    id: "5",
    name: "Chinese Chicken",
    details: [""],
    time: "60",
    src: 'https://picsum.photos/200/300?random=5',
    tools: ["cog"],
    ingredients: ["Chicken", "Honey", "Soya", "Rice vinegar", "Ginger", "Garlic", "Rice"],
  },
  {
    id: "6",
    name: "Fish'n chips",
    details: [""],
    time: "60",
    src: 'https://picsum.photos/200/300?random=6',
    tools: ["cog"],
    ingredients: ["Flour", "Egg", "Beer", "Fish", "Potato", "Beans"],
  },
  {
    id: "7",
    name: "Peking pork",
    details: [""],
    time: "90",
    src: 'https://picsum.photos/200/300?random=7',
    tools: ["cog"],
    ingredients: ["Pork", "Red pepper", "Ginger", "Garlic", "Onion", "Sugar", "Flour", "Soya", "Red wine"],
  },
  {
    id: "8",
    name: "Goulash",
    details: [""],
    time: "90",
    src: 'https://picsum.photos/200/300?random=8',
    tools: ["cog"],
    ingredients: ["Beef", "Onion", "Ketchup", "Black pepper", "Flour"],
  },
  {
    id: "9",
    name: "Crouton",
    details: [""],
    time: "10",
    src: 'https://picsum.photos/200/300?random=9',
    tools: ["cog"],
    ingredients: ["Bread", "Egg", "Valina suggar", "Sugar"],
  },
  {
    id: "10",
    name: "Salmon rolls",
    details: [""],
    time: "15",
    src: 'https://picsum.photos/200/300?random=9',
    tools: ["cog"],
    ingredients: ["Salmon", "Philadelphia cheese", "Pita bread", "Dill"],
  },
  {
    id: "11",
    name: "Paella",
    details: [""],
    time: "80",
    src: 'https://picsum.photos/200/300?random=9',
    tools: ["cog"],
    ingredients: ["Chicken", "Chicken stock", "Paprika", "Garlic", "Safran", "Tomato"],
  },
  {
    id: "12",
    name: "Soup with meatballs",
    details: [""],
    time: "90",
    src: 'https://picsum.photos/200/300?random=9',
    tools: ["cog"],
    ingredients: ["Minced beef", "Minced pork", "Onion", "Potato", "Carrot", "Pasta"],
  },
];

export default RecipeData;

